package Calculator;


/**
* Calculator/CalculatorInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Calculator.idl
* Saturday, May 27, 2023 9:52:08 AM GMT+01:00
*/

public interface CalculatorInterfaceOperations 
{
  double add (double num1, double num2);
  double subtract (double num1, double num2);
  double multiply (double num1, double num2);
  double divide (double num1, double num2);
} // interface CalculatorInterfaceOperations
