package Calculator;

/**
* Calculator/CalculatorInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Calculator.idl
* Saturday, May 27, 2023 9:52:08 AM GMT+01:00
*/

public final class CalculatorInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public Calculator.CalculatorInterface value = null;

  public CalculatorInterfaceHolder ()
  {
  }

  public CalculatorInterfaceHolder (Calculator.CalculatorInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Calculator.CalculatorInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Calculator.CalculatorInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Calculator.CalculatorInterfaceHelper.type ();
  }

}
