package Calculator;


/**
* Calculator/CalculatorInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Calculator.idl
* Saturday, May 27, 2023 9:52:08 AM GMT+01:00
*/

abstract public class CalculatorInterfaceHelper
{
  private static String  _id = "IDL:Calculator/CalculatorInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, Calculator.CalculatorInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Calculator.CalculatorInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Calculator.CalculatorInterfaceHelper.id (), "CalculatorInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Calculator.CalculatorInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CalculatorInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Calculator.CalculatorInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Calculator.CalculatorInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Calculator.CalculatorInterface)
      return (Calculator.CalculatorInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Calculator._CalculatorInterfaceStub stub = new Calculator._CalculatorInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Calculator.CalculatorInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Calculator.CalculatorInterface)
      return (Calculator.CalculatorInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Calculator._CalculatorInterfaceStub stub = new Calculator._CalculatorInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
