package Calculator;


/**
* Calculator/CalculatorInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Calculator.idl
* Saturday, May 27, 2023 9:52:08 AM GMT+01:00
*/

public interface CalculatorInterface extends CalculatorInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CalculatorInterface
