package HelloApp;

/**
* HelloApp/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/hello.idl
* Monday, April 24, 2023 11:24:03 PM GMT+01:00
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{

	void shutdown();
} // interface Hello
