package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/hello.idl
* Monday, April 24, 2023 11:24:03 PM GMT+01:00
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
