package Calculator;


/**
* Calculator/CalculatorInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Calculator.idl
* Tuesday, April 25, 2023 1:17:26 AM GMT+01:00
*/

public abstract class CalculatorInterfacePOA extends org.omg.PortableServer.Servant
 implements Calculator.CalculatorInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("add", new java.lang.Integer (0));
    _methods.put ("sup", new java.lang.Integer (1));
    _methods.put ("div", new java.lang.Integer (2));
    _methods.put ("mul", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Calculator/CalculatorInterface/add
       {
         float num1 = in.read_float ();
         float num2 = in.read_float ();
         float $result = (float)0;
         $result = this.add (num1, num2);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 1:  // Calculator/CalculatorInterface/sup
       {
         float num1 = in.read_float ();
         float num2 = in.read_float ();
         float $result = (float)0;
         $result = this.sup (num1, num2);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 2:  // Calculator/CalculatorInterface/div
       {
         float num1 = in.read_float ();
         float num2 = in.read_float ();
         float $result = (float)0;
         $result = this.div (num1, num2);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 3:  // Calculator/CalculatorInterface/mul
       {
         float num1 = in.read_float ();
         float num2 = in.read_float ();
         float $result = (float)0;
         $result = this.mul (num1, num2);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Calculator/CalculatorInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CalculatorInterface _this() 
  {
    return CalculatorInterfaceHelper.narrow(
    super._this_object());
  }

  public CalculatorInterface _this(org.omg.CORBA.ORB orb) 
  {
    return CalculatorInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class CalculatorInterfacePOA
