package Calculator;


/**
* Calculator/CalculatorInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Calculator.idl
* Tuesday, April 25, 2023 1:17:26 AM GMT+01:00
*/

public interface CalculatorInterfaceOperations 
{
  float add (float num1, float num2);
  float sup (float num1, float num2);
  float div (float num1, float num2);
  float mul (float num1, float num2);
} // interface CalculatorInterfaceOperations
