package Calculator;


/**
* Calculator/CalculatorInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Calculator.idl
* Tuesday, April 25, 2023 1:17:26 AM GMT+01:00
*/

public interface CalculatorInterface extends CalculatorInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CalculatorInterface
