package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Monday, April 17, 2023 10:49:38 PM WAT
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
